name: Terraform Deploy

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-deploy
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        with:
          terraform_version: ~1.14

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4
        with:
          role-to-assume: ${{ secrets.AWS_APPLY_ROLE_ARN }}
          aws-region: ap-northeast-1
          role-session-name: github-actions-deploy

      - name: Terraform Init
        run: terraform init -input=false -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}"

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan.binary

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve tfplan.binary
