name: Terraform Plan (PR)

on:
  pull_request:
    paths:
      - 'terraform/**'
      - '.github/workflows/plan.yml'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        with:
          terraform_version: ~1.14

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4
        with:
          role-to-assume: ${{ secrets.AWS_PLAN_ROLE_ARN }}
          aws-region: ap-northeast-1
          role-session-name: github-actions-plan

      - name: Terraform Init
        run: terraform init -input=false -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}"

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan.binary

      - name: Post Terraform Plan Comment
        uses: towardsthecloud/terraform-plan-pr-commenter@e0e93b3396eb8dfbf70109c06340dc64ce26c818 # v1
        with:
          planfile: tfplan.binary
          working-directory: terraform
          aws-region: ap-northeast-1
